-- Script completo para configurar la base de datos de Fundación Azulanza en Supabase

-- 1. Tabla de Solicitudes de Asesoría
CREATE TABLE IF NOT EXISTS counseling_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT NOT NULL,
    date DATE NOT NULL,
    time TEXT NOT NULL,
    modality TEXT NOT NULL,
    status TEXT DEFAULT 'Pendiente',
    message TEXT
);

-- 2. Tabla de Donaciones
CREATE TABLE IF NOT EXISTS donations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    donor_name TEXT,
    amount DECIMAL(12, 2) NOT NULL,
    payment_method TEXT, -- 'Tarjeta', 'PSE', 'Nequi', 'Daviplata'
    status TEXT DEFAULT 'Completado',
    message TEXT
);

-- 3. Tabla de Galería
CREATE TABLE IF NOT EXISTS gallery (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    title TEXT NOT NULL,
    category TEXT NOT NULL, -- 'Eventos', 'Jornadas', 'Entregas', 'Campañas'
    image_url TEXT NOT NULL
);

-- 4. Tabla de Voluntarios
CREATE TABLE IF NOT EXISTS volunteers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    full_name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT NOT NULL,
    area_of_interest TEXT NOT NULL, -- 'Salud Mental', 'Educación', 'Logística', 'Otro'
    message TEXT,
    status TEXT DEFAULT 'Pendiente' -- 'Pendiente', 'Contactado', 'Activo', 'Inactivo'
);

-- 5. Tabla de Perfiles (para Administradores)
CREATE TABLE IF NOT EXISTS profiles (
    id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    full_name TEXT,
    avatar_url TEXT,
    role TEXT DEFAULT 'admin'
);

-- FUNCIÓN PARA CREAR PERFIL AUTOMÁTICAMENTE AL REGISTRARSE
-- Ejecuta esto en el SQL Editor de Supabase
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, avatar_url, role)
  VALUES (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url', 'admin');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- TRIGGER PARA CREAR PERFIL AL REGISTRAR USUARIO
CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- 6. SQL para crear un usuario administrador manualmente (Opcional si no usas el dashboard)
-- Nota: La contraseña debe ser un hash bcrypt. Este ejemplo es ilustrativo.
-- Se recomienda usar Authentication -> Users -> Add User en el Dashboard de Supabase.

/*
-- Ejemplo de inserción directa (Requiere pgcrypto habilitado)
INSERT INTO auth.users (id, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at, role, confirmation_token, email_change, email_change_token_new, recovery_token)
VALUES (
  gen_random_uuid(),
  'admin@azulanza.org',
  crypt('Azulanza2024!', gen_salt('bf')),
  now(),
  '{"provider":"email","providers":["email"]}',
  '{"full_name":"Administrador Principal"}',
  now(),
  now(),
  'authenticated',
  '',
  '',
  '',
  ''
);
*/

-- 7. Configuración de Plantilla de Correo (Copia este contenido en tu Dashboard)
-- Ve a: Authentication -> Email Templates -> Confirm signup (o Welcome)

/*
--- ASUNTO: ¡Bienvenido(a) a la familia de Fundación Azulanza! 💙 ---

<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; line-height: 1.6; color: #333; }
    .container { max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e0e0e0; border-radius: 10px; }
    .header { text-align: center; padding-bottom: 20px; border-bottom: 2px solid #0056b3; }
    .content { padding: 20px 0; }
    .footer { text-align: center; font-size: 12px; color: #888; margin-top: 20px; }
    .button { background-color: #0056b3; color: white; padding: 12px 24px; text-decoration: none; border-radius: 5px; display: inline-block; font-weight: bold; }
    .highlight { color: #ff3366; font-weight: bold; }
  </style>
</head>
<body>
  <div className="container">
    <div className="header">
      <h1 style="color: #0056b3;">Fundación Azulanza</h1>
    </div>
    <div className="content">
      <h2>¡Hola, <span className="highlight">{{ .Data.full_name }}</span>!</h2>
      <p>Es un gusto darte la bienvenida a nuestra plataforma administrativa. Estamos muy felices de tenerte con nosotros para seguir transformando vidas a través de la salud mental y la solidaridad.</p>
      <p>Tu cuenta ha sido creada exitosamente. Para comenzar a gestionar la plataforma, por favor confirma tu correo haciendo clic en el siguiente botón:</p>
      <div style="text-align: center; margin: 30px 0;">
        <a href="{{ .ConfirmationURL }}" className="button">Confirmar mi Cuenta</a>
      </div>
      <p>Si el botón no funciona, puedes copiar y pegar este enlace en tu navegador:</p>
      <p style="font-size: 11px; word-break: break-all;">{{ .ConfirmationURL }}</p>
      <p>¡Gracias por ser parte del cambio!</p>
    </div>
    <div className="footer">
      <p>&copy; 2024 Fundación Azulanza. Todos los derechos reservados.</p>
      <p>Este es un correo automático, por favor no respondas a esta dirección.</p>
    </div>
  </div>
</body>
</html>
*/

-- 8. Tabla de Slides para el Hero
CREATE TABLE IF NOT EXISTS hero_slides (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    title TEXT NOT NULL,
    subtitle TEXT NOT NULL,
    image_url TEXT NOT NULL,
    cta_text TEXT DEFAULT 'Donar Ahora',
    cta_link TEXT DEFAULT '/donaciones',
    active BOOLEAN DEFAULT true,
    sort_order INT DEFAULT 0
);

ALTER TABLE hero_slides ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public can view active slides" ON hero_slides FOR SELECT USING (active = true);
CREATE POLICY "Admins can manage slides" ON hero_slides FOR ALL USING (true);

-- Seeds para Hero Slides
INSERT INTO hero_slides (title, subtitle, image_url, cta_text, cta_link, sort_order)
VALUES
('Construyendo Esperanza', 'Transformando vidas a través de la solidaridad y el apoyo mutuo.', 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?ixlib=rb-4.0.3&auto=format&fit=crop&w=1920&q=80', 'Donar Ahora', '/donaciones', 1),
('Salud Mental para Todos', 'Brindamos acompañamiento psicológico profesional y accesible.', 'https://images.unsplash.com/photo-1593113598332-cd288d649433?ixlib=rb-4.0.3&auto=format&fit=crop&w=1920&q=80', 'Solicitar Ayuda', '/asesoria', 2),
('Únete al Cambio', 'Tu apoyo hace posible que lleguemos a quienes más lo necesitan.', 'https://images.unsplash.com/photo-1544027993-37dbfe43562a?ixlib=rb-4.0.3&auto=format&fit=crop&w=1920&q=80', 'Ser Voluntario', '/voluntarios', 3);

-- 9. Tabla de Testimonios
CREATE TABLE IF NOT EXISTS testimonials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    name TEXT NOT NULL,
    role TEXT NOT NULL, -- Beneficiario, Voluntario, Donante
    message TEXT NOT NULL,
    avatar_url TEXT,
    rating INT DEFAULT 5,
    active BOOLEAN DEFAULT true
);

ALTER TABLE testimonials ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public can view active testimonials" ON testimonials FOR SELECT USING (active = true);
CREATE POLICY "Admins can manage testimonials" ON testimonials FOR ALL USING (true);

-- Seeds para Testimonios
INSERT INTO testimonials (name, role, message, avatar_url, rating)
VALUES
('Laura R.', 'Beneficiaria', 'La asesoría psicológica de la fundación cambió mi vida. Me brindaron las herramientas para superar un momento muy difícil.', 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?ixlib=rb-4.0.3&auto=format&fit=crop&w=150&q=80', 5),
('Andrés M.', 'Voluntario', 'Ser parte de Azulanza es una experiencia enriquecedora. Ver la sonrisa de los niños en cada jornada no tiene precio.', 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-4.0.3&auto=format&fit=crop&w=150&q=80', 5),
('Claudia P.', 'Donante', 'Confío plenamente en la labor de la fundación. Su transparencia y compromiso con la comunidad son admirables.', 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?ixlib=rb-4.0.3&auto=format&fit=crop&w=150&q=80', 5);

-- Habilitar RLS en todas las tablas
ALTER TABLE counseling_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE donations ENABLE ROW LEVEL SECURITY;
ALTER TABLE gallery ENABLE ROW LEVEL SECURITY;
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE hero_slides ENABLE ROW LEVEL SECURITY;
ALTER TABLE testimonials ENABLE ROW LEVEL SECURITY;

-- POLÍTICAS RLS

-- Storage: crear bucket para galería (ejecutar una sola vez)
-- Alternativa: crear bucket insertando en storage.buckets (compatible con todas las versiones)
insert into storage.buckets (id, name, public)
values ('gallery','gallery', true)
on conflict (id) do nothing;

-- Políticas para Storage Objects del bucket 'gallery'
drop policy if exists "Public can view gallery images" on storage.objects;
create policy "Public can view gallery images" on storage.objects
for select
using (bucket_id = 'gallery');

drop policy if exists "Authenticated can upload to gallery" on storage.objects;
create policy "Authenticated can upload to gallery" on storage.objects
for insert
to authenticated
with check (bucket_id = 'gallery');

drop policy if exists "Authenticated can update gallery images" on storage.objects;
create policy "Authenticated can update gallery images" on storage.objects
for update
to authenticated
using (bucket_id = 'gallery')
with check (bucket_id = 'gallery');

drop policy if exists "Authenticated can delete gallery images" on storage.objects;
create policy "Authenticated can delete gallery images" on storage.objects
for delete
to authenticated
using (bucket_id = 'gallery');

-- Políticas adicionales para la tabla 'gallery'
drop policy if exists "Public can view gallery" on gallery;
create policy "Public can view gallery" on gallery
for select
using (true);

drop policy if exists "Authenticated can insert gallery" on gallery;
create policy "Authenticated can insert gallery" on gallery
for insert
to authenticated
with check (true);

drop policy if exists "Authenticated can update gallery" on gallery;
create policy "Authenticated can update gallery" on gallery
for update
to authenticated
using (true)
with check (true);

drop policy if exists "Authenticated can delete gallery" on gallery;
create policy "Authenticated can delete gallery" on gallery
for delete
to authenticated
using (true);

-- Counseling Requests
CREATE POLICY "Public can insert requests" ON counseling_requests FOR INSERT WITH CHECK (true);
CREATE POLICY "Admins can view requests" ON counseling_requests FOR SELECT USING (true);
CREATE POLICY "Admins can update requests" ON counseling_requests FOR UPDATE USING (true);

-- Donations
CREATE POLICY "Public can view completed donations" ON donations FOR SELECT USING (status = 'Completado');
CREATE POLICY "Public can insert donations" ON donations FOR INSERT WITH CHECK (true);
CREATE POLICY "Admins can manage donations" ON donations FOR ALL USING (true);

-- Gallery
CREATE POLICY "Public can view gallery" ON gallery FOR SELECT USING (true);
CREATE POLICY "Admins can manage gallery" ON gallery FOR ALL USING (true);

-- Volunteers
ALTER TABLE volunteers ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public can insert volunteer applications" ON volunteers FOR INSERT WITH CHECK (true);
CREATE POLICY "Admins can manage volunteers" ON volunteers FOR ALL USING (true);

-- Profiles
CREATE POLICY "Users can view their own profile" ON profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update their own profile" ON profiles FOR UPDATE USING (auth.uid() = id);

-- SEEDS (Datos iniciales)

-- Seeds para Counseling
INSERT INTO counseling_requests (name, email, phone, date, time, modality, status, message)
VALUES
('María González', 'maria@example.com', '3001234567', '2023-11-15', '09:00 AM', 'Virtual', 'Pendiente', 'Necesito apoyo emocional por duelo reciente.'),
('Carlos Pérez', 'carlos@example.com', '3109876543', '2023-11-16', '10:00 AM', 'Presencial', 'Confirmado', 'Ansiedad generalizada.'),
('Ana Rodríguez', 'ana@example.com', '3205551234', '2023-11-18', '02:00 PM', 'Virtual', 'Completado', 'Seguimiento mensual.');

-- Seeds para Galería
INSERT INTO gallery (title, category, image_url)
VALUES
('Taller de Arte Terapia', 'Eventos', 'https://images.unsplash.com/photo-1511632765486-a019809dd005?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80'),
('Jornada de Salud', 'Jornadas', 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80'),
('Entrega de Kits Escolares', 'Entregas', 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80'),
('Campaña de Salud Mental', 'Campañas', 'https://images.unsplash.com/photo-1593113598332-cd288d649433?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80');

-- Seeds para Donaciones
INSERT INTO donations (donor_name, amount, payment_method, message)
VALUES
('Anónimo', 50000.00, 'Tarjeta', 'Mucha fuerza para su labor.'),
('Juan Pérez', 100000.00, 'PSE', 'Apoyo para los kits escolares.'),
('Fundación Aliada', 500000.00, 'Transferencia', 'Donación corporativa mensual.');
