-- Tabla de Noticias
CREATE TABLE IF NOT EXISTS news (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    title TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    summary TEXT,
    content TEXT NOT NULL,
    image_url TEXT,
    published_at TIMESTAMPTZ DEFAULT NOW(),
    active BOOLEAN DEFAULT true,
    author TEXT DEFAULT 'Fundación Azulanza'
);

ALTER TABLE news ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public can view active news" ON news FOR SELECT USING (active = true);
CREATE POLICY "Admins can manage news" ON news FOR ALL USING (true);

-- Insertar datos de prueba
INSERT INTO news (title, slug, summary, content, image_url, active)
VALUES
('Jornada de Salud Mental en Barranquilla', 'jornada-salud-mental-barranquilla', 'Exitosa jornada de apoyo psicológico gratuito en el barrio El Bosque.', 'Este fin de semana realizamos una jornada masiva de atención psicológica...', 'https://images.unsplash.com/photo-1544027993-37dbfe43562a?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', true),
('Donación de Kits Escolares', 'donacion-kits-escolares-2024', 'Entregamos más de 500 kits a niños de escasos recursos.', 'Gracias a nuestros donantes, logramos llevar alegría y educación...', 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', true);
